kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-mysql-test
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi